/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Belzee
 */
public class FrmPrincipal extends javax.swing.JFrame {

    public static AdmonArchivoTexto aat = new AdmonArchivoTexto();
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        opcNuevo = new javax.swing.JMenuItem();
        opcAbrir = new javax.swing.JMenuItem();
        opcSalir = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        opcVerAyuda = new javax.swing.JMenuItem();
        opcAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDITOR DE TEXTOS");

        mnuArchivo.setText("Archivo");

        opcNuevo.setText("Nuevo");
        opcNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcNuevoActionPerformed(evt);
            }
        });
        mnuArchivo.add(opcNuevo);

        opcAbrir.setText("Abrir");
        opcAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAbrirActionPerformed(evt);
            }
        });
        mnuArchivo.add(opcAbrir);

        opcSalir.setText("Salir");
        opcSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(opcSalir);

        jMenuBar1.add(mnuArchivo);

        mnuAyuda.setText("Ayuda");

        opcVerAyuda.setText("Ver la ayuda");
        opcVerAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcVerAyudaActionPerformed(evt);
            }
        });
        mnuAyuda.add(opcVerAyuda);

        opcAcercaDe.setText("Acerca de...");
        opcAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAcercaDeActionPerformed(evt);
            }
        });
        mnuAyuda.add(opcAcercaDe);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opcSalirActionPerformed

    private void opcNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcNuevoActionPerformed
        new FrmNuevo(this, true).setVisible(true);
    }//GEN-LAST:event_opcNuevoActionPerformed

    private void opcAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAbrirActionPerformed
        String nombreArchivo;
        int opc;
        JFileChooser dlgAbrir = new JFileChooser();
        
        dlgAbrir.setFileSelectionMode(JFileChooser.FILES_ONLY);
        dlgAbrir.addChoosableFileFilter(new FiltroTxt());
        opc = dlgAbrir.showOpenDialog(this);
        if (opc == JFileChooser.APPROVE_OPTION)  {
            nombreArchivo = dlgAbrir.getSelectedFile().getPath();
            new FrmAbrir(this, true, nombreArchivo).setVisible(true);
        }
    }//GEN-LAST:event_opcAbrirActionPerformed

    private void opcVerAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcVerAyudaActionPerformed
        String texto;
        
        new FrmAyuda(this, true).setVisible(true);
    }//GEN-LAST:event_opcVerAyudaActionPerformed

    private void opcAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAcercaDeActionPerformed
        JOptionPane.showMessageDialog(this,
                    "Editor de textos \n" + "Version: 1.0\n" + "Desarrollador: Luis Gerardo Esteban Flores\n" + "Fecha: Mayo 2023", 
                    "Acerca de...", 
                    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_opcAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem opcAbrir;
    private javax.swing.JMenuItem opcAcercaDe;
    private javax.swing.JMenuItem opcNuevo;
    private javax.swing.JMenuItem opcSalir;
    private javax.swing.JMenuItem opcVerAyuda;
    // End of variables declaration//GEN-END:variables
}
